version: "3"

services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_PASSWORD=cryptoc
      - POSTGRES_USER=cryptoc
      - POSTGRES_DB=cryptoc
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
