version: "3"

services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_PASSWORD=cryptoc
      - POSTGRES_USER=cryptoc
      - POSTGRES_DB=cryptoc
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  ganache:
    image: trufflesuite/ganache-cli:latest
    command:
      [
        "node",
        "/app/ganache-core.docker.cli.js",
        "--accounts=3",
        "--gasPrice=0",
        "--account_keys_path=/app/keys",
        "--account=${PPV_PRIVATE_KEY_1},100000000000000000000",
        "--account=${PPV_PRIVATE_KEY_2},100000000000000000000",
        "--account=${PPV_PRIVATE_KEY_3},100000000000000000000",
      ]
    ports:
      - 8545:8545
