// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	PayPerViewEvents    string
	Payments            string
	Permissions         string
	PermissionsUsers    string
	SmartContractEvents string
	SmartContracts      string
	Users               string
}{
	PayPerViewEvents:    "pay_per_view_events",
	Payments:            "payments",
	Permissions:         "permissions",
	PermissionsUsers:    "permissions_users",
	SmartContractEvents: "smart_contract_events",
	SmartContracts:      "smart_contracts",
	Users:               "users",
}
