// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// SmartContractEvent is an object representing the database table.
type SmartContractEvent struct {
	ID              int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	SmartContractID int64       `boil:"smart_contract_id" json:"smartContractID" toml:"smartContractID" yaml:"smartContractID"`
	Data            null.String `boil:"data" json:"data,omitempty" toml:"data" yaml:"data,omitempty"`

	R *smartContractEventR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L smartContractEventL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SmartContractEventColumns = struct {
	ID              string
	SmartContractID string
	Data            string
}{
	ID:              "id",
	SmartContractID: "smart_contract_id",
	Data:            "data",
}

// Generated where

var SmartContractEventWhere = struct {
	ID              whereHelperint64
	SmartContractID whereHelperint64
	Data            whereHelpernull_String
}{
	ID:              whereHelperint64{field: "\"smart_contract_events\".\"id\""},
	SmartContractID: whereHelperint64{field: "\"smart_contract_events\".\"smart_contract_id\""},
	Data:            whereHelpernull_String{field: "\"smart_contract_events\".\"data\""},
}

// SmartContractEventRels is where relationship names are stored.
var SmartContractEventRels = struct {
	SmartContract string
}{
	SmartContract: "SmartContract",
}

// smartContractEventR is where relationships are stored.
type smartContractEventR struct {
	SmartContract *SmartContract
}

// NewStruct creates a new relationship struct
func (*smartContractEventR) NewStruct() *smartContractEventR {
	return &smartContractEventR{}
}

// smartContractEventL is where Load methods for each relationship are stored.
type smartContractEventL struct{}

var (
	smartContractEventAllColumns            = []string{"id", "smart_contract_id", "data"}
	smartContractEventColumnsWithoutDefault = []string{"smart_contract_id", "data"}
	smartContractEventColumnsWithDefault    = []string{"id"}
	smartContractEventPrimaryKeyColumns     = []string{"id"}
)

type (
	// SmartContractEventSlice is an alias for a slice of pointers to SmartContractEvent.
	// This should generally be used opposed to []SmartContractEvent.
	SmartContractEventSlice []*SmartContractEvent

	smartContractEventQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	smartContractEventType                 = reflect.TypeOf(&SmartContractEvent{})
	smartContractEventMapping              = queries.MakeStructMapping(smartContractEventType)
	smartContractEventPrimaryKeyMapping, _ = queries.BindMapping(smartContractEventType, smartContractEventMapping, smartContractEventPrimaryKeyColumns)
	smartContractEventInsertCacheMut       sync.RWMutex
	smartContractEventInsertCache          = make(map[string]insertCache)
	smartContractEventUpdateCacheMut       sync.RWMutex
	smartContractEventUpdateCache          = make(map[string]updateCache)
	smartContractEventUpsertCacheMut       sync.RWMutex
	smartContractEventUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single smartContractEvent record from the query.
func (q smartContractEventQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SmartContractEvent, error) {
	o := &SmartContractEvent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for smart_contract_events")
	}

	return o, nil
}

// All returns all SmartContractEvent records from the query.
func (q smartContractEventQuery) All(ctx context.Context, exec boil.ContextExecutor) (SmartContractEventSlice, error) {
	var o []*SmartContractEvent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SmartContractEvent slice")
	}

	return o, nil
}

// Count returns the count of all SmartContractEvent records in the query.
func (q smartContractEventQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count smart_contract_events rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q smartContractEventQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if smart_contract_events exists")
	}

	return count > 0, nil
}

// SmartContract pointed to by the foreign key.
func (o *SmartContractEvent) SmartContract(mods ...qm.QueryMod) smartContractQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SmartContractID),
	}

	queryMods = append(queryMods, mods...)

	query := SmartContracts(queryMods...)
	queries.SetFrom(query.Query, "\"smart_contracts\"")

	return query
}

// LoadSmartContract allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (smartContractEventL) LoadSmartContract(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSmartContractEvent interface{}, mods queries.Applicator) error {
	var slice []*SmartContractEvent
	var object *SmartContractEvent

	if singular {
		object = maybeSmartContractEvent.(*SmartContractEvent)
	} else {
		slice = *maybeSmartContractEvent.(*[]*SmartContractEvent)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &smartContractEventR{}
		}
		args = append(args, object.SmartContractID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &smartContractEventR{}
			}

			for _, a := range args {
				if a == obj.SmartContractID {
					continue Outer
				}
			}

			args = append(args, obj.SmartContractID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`smart_contracts`), qm.WhereIn(`smart_contracts.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SmartContract")
	}

	var resultSlice []*SmartContract
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SmartContract")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for smart_contracts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for smart_contracts")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SmartContract = foreign
		if foreign.R == nil {
			foreign.R = &smartContractR{}
		}
		foreign.R.SmartContractEvents = append(foreign.R.SmartContractEvents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SmartContractID == foreign.ID {
				local.R.SmartContract = foreign
				if foreign.R == nil {
					foreign.R = &smartContractR{}
				}
				foreign.R.SmartContractEvents = append(foreign.R.SmartContractEvents, local)
				break
			}
		}
	}

	return nil
}

// SetSmartContract of the smartContractEvent to the related item.
// Sets o.R.SmartContract to related.
// Adds o to related.R.SmartContractEvents.
func (o *SmartContractEvent) SetSmartContract(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SmartContract) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"smart_contract_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"smart_contract_id"}),
		strmangle.WhereClause("\"", "\"", 2, smartContractEventPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SmartContractID = related.ID
	if o.R == nil {
		o.R = &smartContractEventR{
			SmartContract: related,
		}
	} else {
		o.R.SmartContract = related
	}

	if related.R == nil {
		related.R = &smartContractR{
			SmartContractEvents: SmartContractEventSlice{o},
		}
	} else {
		related.R.SmartContractEvents = append(related.R.SmartContractEvents, o)
	}

	return nil
}

// SmartContractEvents retrieves all the records using an executor.
func SmartContractEvents(mods ...qm.QueryMod) smartContractEventQuery {
	mods = append(mods, qm.From("\"smart_contract_events\""))
	return smartContractEventQuery{NewQuery(mods...)}
}

// FindSmartContractEvent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSmartContractEvent(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*SmartContractEvent, error) {
	smartContractEventObj := &SmartContractEvent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"smart_contract_events\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, smartContractEventObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from smart_contract_events")
	}

	return smartContractEventObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SmartContractEvent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no smart_contract_events provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(smartContractEventColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	smartContractEventInsertCacheMut.RLock()
	cache, cached := smartContractEventInsertCache[key]
	smartContractEventInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			smartContractEventAllColumns,
			smartContractEventColumnsWithDefault,
			smartContractEventColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(smartContractEventType, smartContractEventMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(smartContractEventType, smartContractEventMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"smart_contract_events\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"smart_contract_events\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into smart_contract_events")
	}

	if !cached {
		smartContractEventInsertCacheMut.Lock()
		smartContractEventInsertCache[key] = cache
		smartContractEventInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the SmartContractEvent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SmartContractEvent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	smartContractEventUpdateCacheMut.RLock()
	cache, cached := smartContractEventUpdateCache[key]
	smartContractEventUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			smartContractEventAllColumns,
			smartContractEventPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update smart_contract_events, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"smart_contract_events\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, smartContractEventPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(smartContractEventType, smartContractEventMapping, append(wl, smartContractEventPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update smart_contract_events row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for smart_contract_events")
	}

	if !cached {
		smartContractEventUpdateCacheMut.Lock()
		smartContractEventUpdateCache[key] = cache
		smartContractEventUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q smartContractEventQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for smart_contract_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for smart_contract_events")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SmartContractEventSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), smartContractEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"smart_contract_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, smartContractEventPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in smartContractEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all smartContractEvent")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SmartContractEvent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no smart_contract_events provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(smartContractEventColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	smartContractEventUpsertCacheMut.RLock()
	cache, cached := smartContractEventUpsertCache[key]
	smartContractEventUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			smartContractEventAllColumns,
			smartContractEventColumnsWithDefault,
			smartContractEventColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			smartContractEventAllColumns,
			smartContractEventPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert smart_contract_events, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(smartContractEventPrimaryKeyColumns))
			copy(conflict, smartContractEventPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"smart_contract_events\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(smartContractEventType, smartContractEventMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(smartContractEventType, smartContractEventMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert smart_contract_events")
	}

	if !cached {
		smartContractEventUpsertCacheMut.Lock()
		smartContractEventUpsertCache[key] = cache
		smartContractEventUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single SmartContractEvent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SmartContractEvent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SmartContractEvent provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), smartContractEventPrimaryKeyMapping)
	sql := "DELETE FROM \"smart_contract_events\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from smart_contract_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for smart_contract_events")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q smartContractEventQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no smartContractEventQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from smart_contract_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for smart_contract_events")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SmartContractEventSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), smartContractEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"smart_contract_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, smartContractEventPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from smartContractEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for smart_contract_events")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SmartContractEvent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSmartContractEvent(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SmartContractEventSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SmartContractEventSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), smartContractEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"smart_contract_events\".* FROM \"smart_contract_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, smartContractEventPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SmartContractEventSlice")
	}

	*o = slice

	return nil
}

// SmartContractEventExists checks if the SmartContractEvent row exists.
func SmartContractEventExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"smart_contract_events\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if smart_contract_events exists")
	}

	return exists, nil
}
